spring.application.name=Educational Quality Project

# MongoDB Configuration
# Cole aqui sua Connection String do MongoDB Atlas:
# Exemplo: mongodb+srv://<user>:<password>@cluster0.abcde.mongodb.net/database?retryWrites=true&w=majority
spring.data.mongodb.urimongodb+srv:/jefersonalvessantos62_db_user:1I80hS4mf4Q5FXiq@banco.dnnwyy8.mongodb.net/?appName=banco
# Server Configuration
server.port=8081
